if (NOT DEFINED VERTEX_SPV OR NOT DEFINED FRAGMENT_SPV OR NOT DEFINED OUTPUT_HEADER)
    message(FATAL_ERROR "VERTEX_SPV, FRAGMENT_SPV and OUTPUT_HEADER are required")
endif()
if (NOT DEFINED VERTEX_ARRAY_NAME)
    set(VERTEX_ARRAY_NAME "kVrPanelVertexSpirv")
endif()
if (NOT DEFINED FRAGMENT_ARRAY_NAME)
    set(FRAGMENT_ARRAY_NAME "kVrPanelFragmentSpirv")
endif()
if (NOT DEFINED HEADER_GUARD)
    set(HEADER_GUARD "CRY_VR_PANEL_SHADERS_H")
endif()

function(spirv_to_array INPUT_FILE ARRAY_NAME OUTPUT_TEXT)
    file(READ "${INPUT_FILE}" _hex HEX)
    string(LENGTH "${_hex}" _hex_length)
    math(EXPR _remainder "${_hex_length} % 8")
    if (NOT _remainder EQUAL 0)
        message(FATAL_ERROR "SPIR-V byte stream has a partial word: ${INPUT_FILE}")
    endif()
    set(_array "static const uint32_t ${ARRAY_NAME}[] = {\n")
    set(_index 0)
    while (_index LESS _hex_length)
        string(SUBSTRING "${_hex}" ${_index} 2 _b0)
        math(EXPR _i1 "${_index} + 2")
        math(EXPR _i2 "${_index} + 4")
        math(EXPR _i3 "${_index} + 6")
        string(SUBSTRING "${_hex}" ${_i1} 2 _b1)
        string(SUBSTRING "${_hex}" ${_i2} 2 _b2)
        string(SUBSTRING "${_hex}" ${_i3} 2 _b3)
        string(APPEND _array "    0x${_b3}${_b2}${_b1}${_b0}u,\n")
        math(EXPR _index "${_index} + 8")
    endwhile()
    string(APPEND _array "};\n")
    set(${OUTPUT_TEXT} "${_array}" PARENT_SCOPE)
endfunction()

spirv_to_array("${VERTEX_SPV}" "${VERTEX_ARRAY_NAME}" _vertex_array)
spirv_to_array("${FRAGMENT_SPV}" "${FRAGMENT_ARRAY_NAME}" _fragment_array)
set(_extra_arrays "")
if (DEFINED EXTRA_VERTEX_SPV AND DEFINED EXTRA_VERTEX_ARRAY_NAME)
    spirv_to_array("${EXTRA_VERTEX_SPV}" "${EXTRA_VERTEX_ARRAY_NAME}" _extra_vertex_array)
    string(APPEND _extra_arrays "${_extra_vertex_array}")
endif()
if (DEFINED EXTRA_FRAGMENT_SPV AND DEFINED EXTRA_FRAGMENT_ARRAY_NAME)
    spirv_to_array("${EXTRA_FRAGMENT_SPV}" "${EXTRA_FRAGMENT_ARRAY_NAME}" _extra_fragment_array)
    string(APPEND _extra_arrays "${_extra_fragment_array}")
endif()
if (DEFINED THIRD_VERTEX_SPV AND DEFINED THIRD_VERTEX_ARRAY_NAME)
    spirv_to_array("${THIRD_VERTEX_SPV}" "${THIRD_VERTEX_ARRAY_NAME}" _third_vertex_array)
    string(APPEND _extra_arrays "${_third_vertex_array}")
endif()
if (DEFINED THIRD_FRAGMENT_SPV AND DEFINED THIRD_FRAGMENT_ARRAY_NAME)
    spirv_to_array("${THIRD_FRAGMENT_SPV}" "${THIRD_FRAGMENT_ARRAY_NAME}" _third_fragment_array)
    string(APPEND _extra_arrays "${_third_fragment_array}")
endif()
if (DEFINED FOURTH_VERTEX_SPV AND DEFINED FOURTH_VERTEX_ARRAY_NAME)
    spirv_to_array("${FOURTH_VERTEX_SPV}" "${FOURTH_VERTEX_ARRAY_NAME}" _fourth_vertex_array)
    string(APPEND _extra_arrays "${_fourth_vertex_array}")
endif()
if (DEFINED FOURTH_FRAGMENT_SPV AND DEFINED FOURTH_FRAGMENT_ARRAY_NAME)
    spirv_to_array("${FOURTH_FRAGMENT_SPV}" "${FOURTH_FRAGMENT_ARRAY_NAME}" _fourth_fragment_array)
    string(APPEND _extra_arrays "${_fourth_fragment_array}")
endif()
if (DEFINED FIFTH_VERTEX_SPV AND DEFINED FIFTH_VERTEX_ARRAY_NAME)
    spirv_to_array("${FIFTH_VERTEX_SPV}" "${FIFTH_VERTEX_ARRAY_NAME}" _fifth_vertex_array)
    string(APPEND _extra_arrays "${_fifth_vertex_array}")
endif()
if (DEFINED FIFTH_FRAGMENT_SPV AND DEFINED FIFTH_FRAGMENT_ARRAY_NAME)
    spirv_to_array("${FIFTH_FRAGMENT_SPV}" "${FIFTH_FRAGMENT_ARRAY_NAME}" _fifth_fragment_array)
    string(APPEND _extra_arrays "${_fifth_fragment_array}")
endif()
if (DEFINED SIXTH_VERTEX_SPV AND DEFINED SIXTH_VERTEX_ARRAY_NAME)
    spirv_to_array("${SIXTH_VERTEX_SPV}" "${SIXTH_VERTEX_ARRAY_NAME}" _sixth_vertex_array)
    string(APPEND _extra_arrays "${_sixth_vertex_array}")
endif()
if (DEFINED SEVENTH_VERTEX_SPV AND DEFINED SEVENTH_VERTEX_ARRAY_NAME)
    spirv_to_array("${SEVENTH_VERTEX_SPV}" "${SEVENTH_VERTEX_ARRAY_NAME}" _seventh_vertex_array)
    string(APPEND _extra_arrays "${_seventh_vertex_array}")
endif()
if (DEFINED SIXTH_FRAGMENT_SPV AND DEFINED SIXTH_FRAGMENT_ARRAY_NAME)
    spirv_to_array("${SIXTH_FRAGMENT_SPV}" "${SIXTH_FRAGMENT_ARRAY_NAME}" _sixth_fragment_array)
    string(APPEND _extra_arrays "${_sixth_fragment_array}")
endif()
if (DEFINED EIGHTH_VERTEX_SPV AND DEFINED EIGHTH_VERTEX_ARRAY_NAME)
    spirv_to_array("${EIGHTH_VERTEX_SPV}" "${EIGHTH_VERTEX_ARRAY_NAME}" _eighth_vertex_array)
    string(APPEND _extra_arrays "${_eighth_vertex_array}")
endif()
if (DEFINED NINTH_VERTEX_SPV AND DEFINED NINTH_VERTEX_ARRAY_NAME)
    spirv_to_array("${NINTH_VERTEX_SPV}" "${NINTH_VERTEX_ARRAY_NAME}" _ninth_vertex_array)
    string(APPEND _extra_arrays "${_ninth_vertex_array}")
endif()
file(WRITE "${OUTPUT_HEADER}"
    "#ifndef ${HEADER_GUARD}\n#define ${HEADER_GUARD}\n#include <cstdint>\nnamespace CryVR {\n${_vertex_array}${_fragment_array}${_extra_arrays}}\n#endif\n")
