add_subdirectory(Cry3DEngine)
add_subdirectory(CryVR)
add_subdirectory(CryAISystem)
add_subdirectory(CryAnimation)
add_subdirectory(CryEntitySystem)
add_subdirectory(CryFont)
add_subdirectory(CrySoundSystem)
add_subdirectory(CryGame)

add_subdirectory(CryInput)
add_subdirectory(CryMovie)
add_subdirectory(CryNetwork)
add_subdirectory(CryPhysics)
add_subdirectory(CryScriptSystem)
add_subdirectory(CrySystem)
add_subdirectory(FARCRY)
if (MSVC)
add_subdirectory(FarCry_WinSV)
endif()
if (NOT MSVC AND ("${DXVK_INC_PATH}" STREQUAL "" OR "${DXVK_LIB_PATH}" STREQUAL ""))
message( WARNING "DXVK_INC_PATH and/or DXVK_LIB_PATH are not set. Building XRenderD3D9 is disabled. If you want to build XRenderD3D9, set DXVK_LIB_PATH to a path containing libdxvk_d3d9.so.0, and DXVK_INC_PATH to a path containing windows_base.h, likely <dxvk_source_dir>/include/native/windows" )
else()
add_subdirectory(RenderDll/XRenderD3D9)
endif()
add_subdirectory(RenderDll/XRenderNULL)
add_subdirectory(RenderDll/XRenderVulkan)
add_subdirectory(RenderDll/XRenderOGL)
if (MSVC)
add_subdirectory(ResourceCompiler)
add_subdirectory(ResourceCompilerPC)
endif()
